In [20]:
!pip install gym

In [0]:
#Frozen lake from open ai gym

In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [0]:
env = gym.make("FrozenLake-v0")

In [24]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [30]:
rewards_all_episodes = []

#Q-Learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        q_table[state, action] = q_table[state, action]*(1-learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("Avg reward per 1000 episodes")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print("Q-table")
print(q_table)









Avg reward per 1000 episodes
1000 :  0.05000000000000004
2000 :  0.18100000000000013
3000 :  0.4230000000000003
4000 :  0.5910000000000004
5000 :  0.6420000000000005
6000 :  0.6720000000000005
7000 :  0.7130000000000005
8000 :  0.6930000000000005
9000 :  0.6730000000000005
10000 :  0.6910000000000005
Q-table
[[0.55939997 0.52011499 0.51113561 0.51868568]
 [0.32532607 0.42990245 0.3804643  0.50650743]
 [0.4074063  0.38603414 0.41893938 0.47409115]
 [0.34412238 0.28163164 0.21721436 0.45113789]
 [0.57371744 0.41524906 0.39879503 0.34902392]
 [0.         0.         0.         0.        ]
 [0.1782817  0.15985588 0.32822907 0.14691474]
 [0.         0.         0.         0.        ]
 [0.3548398  0.36516238 0.41046191 0.6229914 ]
 [0.36808057 0.66599285 0.45245802 0.43439705]
 [0.64862231 0.3488075  0.39564221 0.28146228]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.52194389 0.6107117  0.76010044 0.51778847]
 [0.71255229 0.94110336 0.784148

In [32]:
for episode in range(3):
    state = env.reset()
    print("Episode ", episode+1)
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward ==1:
                print("You reached goal")
                time.sleep(3)
            else:
                print("You fall through hole")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
You fall through hole
